### PR TITLE
Added more Focaltech features

### PR DESCRIPTION
**Pull request by datacute**
Also reversed enableINT and disableINT - they should probably be called Interrupt Polling Mode (generates single interrupt to inform MCU to start polling) and Interrupt Trigger Mode (generates large number of interrupts, while touch continues).

### CODE REVIEW

**Comment by lewisxhe** [comment]
I cannot agree to this request for the time being, it will affect other boards, please give me time, I need to verify and make changes.

**Comment by lewisxhe** [comment]
Please withdraw your request for TTGO.h and only update focaltech.h and cpp

**Comment by datacute** [comment]
@lewisxhe TTGO.h changes reverted. Should I also revert the enableINT and disableINT changes so that pull request is only added new methods?

**Comment by lewisxhe** [comment]
That's it. For the touch interrupt, I don’t use it now, so it doesn’t matter, thank you for the updated new method

**Pull request merged**
